name       : discount
version    : 2.2.6
release    : 3
source     :
    - https://github.com/Orc/discount/archive/v2.2.6.tar.gz : 0beb98a66a6e38ed125e2d0a161ff6b461f6a38538bb72498766f376c94a0ad3
license    : BSD-3-Clause
component  : programming
summary    : DISCOUNT is a implementation of John Gruber's Markdown markup language.
description: |
    DISCOUNT is a implementation of John Gruber's Markdown markup language.
setup      : |
    ./configure.sh --prefix=/usr --libdir=%libdir% --shared
build      : |
    %patch -p1 < $pkgfiles/0001-Fix-ldconfig-call.patch
    make -j1
install    : |
    %make_install
check      : |
    %make test
