name       : discount
version    : 2.2.1
release    : 1
source     :
    - http://www.pell.portland.or.us/~orc/Code/discount/discount-2.2.1.tar.bz2 : 88458c7c2cfc870f8e6cf42b300408c112e05a45c88f8af35abb33de0e96fe0e
license    : BSD-3-Clause
component  : programming
summary    : DISCOUNT is a implementation of John Gruber's Markdown markup language.
description: |
    DISCOUNT is a implementation of John Gruber's Markdown markup language.
setup      : |
    ./configure.sh --prefix=/usr --libdir=%libdir% --shared
build      : |
    %make
install    : |
    %make_install
