name       : discount
version    : 2.2.4
release    : 2
source     :
    - http://www.pell.portland.or.us/~orc/Code/discount/discount-2.2.4.tar.bz2 : 74fd1e3cc2b4eacf7325d3fd89df38b589db60d5dd0f4f14a0115f7da5e230a5
license    : BSD-3-Clause
component  : programming
summary    : DISCOUNT is a implementation of John Gruber's Markdown markup language.
description: |
    DISCOUNT is a implementation of John Gruber's Markdown markup language.
setup      : |
    ./configure.sh --prefix=/usr --libdir=%libdir% --shared
build      : |
    %patch -p1 < $pkgfiles/0001-Fix-ldconfig-call.patch
    %make
install    : |
    %make_install
check      : |
    %make test
